name: blrber
description: Global app to Buy / Sell New and used products.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+30

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # Firebase Plugins
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1
  firebase_auth: ^0.20.1
  firebase_storage: ^7.0.0
  firebase_messaging: ^6.0.16
  firebase_dynamic_links: ^0.7.0+1

  flutter_local_notifications: ^4.0.1+2

  # Google Plugins
  google_sign_in: ^4.5.9

  # Provider Pligins
  provider: ^4.3.3

  # Maps/Location Plugins
  geocoder: ^0.2.1
  geolocator: ^6.2.1
  google_maps_flutter: ^0.5.13
  search_map_place: ^0.3.0
  # google_ml_vision: ^0.0.5 // This package leads to increase app size about 40MB
  # google_ml_kit:

  # ML Plugins
  tflite: ^1.1.1
  firebase_ml_custom: ^0.1.0

  # Utils Plugins
  flag: ^3.2.2
  carousel_slider: ^3.0.0
  photo_view: ^0.11.1
  badges: ^1.2.0
  image_picker: ^0.6.7+22
  path_provider: ^1.6.28
  share: 0.6.5+4
  speech_to_text: ^2.3.0
  custom_radio_grouped_button: ^1.0.6+1
  currency_pickers: ^1.0.6
  flutter_switch: ^0.3.1
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.0.0
  url_launcher: ^5.0.2
  darq: ^1.1.1
  image_cropper: ^1.4.1
  scrollable_positioned_list: ^0.1.10
  connectivity_plus: ^0.8.1
  searchable_dropdown: ^1.1.3
  sqflite: ^2.0.0+3
  basic_utils: ^2.7.1
  avatar_glow: ^2.0.1
  cached_network_image: ^2.5.1
  permission_handler: ^5.1.0+2
  package_info: ^0.4.3+4
  fluttertoast: ^8.0.8
  html: ^0.14.0+4
  dropdown_search:
  country_picker:
  google_mobile_ads:

  

  # Payment Razorpay
  razorpay_flutter: ^1.2.7


dev_dependencies: 
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.2.8

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/app_icon/splash.png"
  android: true
  ios: true
  # android_gravity: fill
  # ios_content_mode: scaleAspectFill

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_iconS.png"    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/default_user_image.png
    - assets/images/image_loading.gif
    - assets/app_icon/app_icon.png
    - assets/ML/labels.txt
    - assets/ML/model_unquant.tflite
    
   
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/google_fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/google_fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/google_fonts/Montserrat/Montserrat-Italic.ttf
          weight: 600
    - family: Lato
      fonts:
        - asset: assets/google_fonts/Lato/Lato-Bold.ttf
        - asset: assets/google_fonts/Lato/Lato-Regular.ttf
        - asset: assets/google_fonts/Lato/Lato-Italic.ttf
          weight: 600     
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
